# frontend/Dockerfile.dev
FROM node:24.0.1-slim

# pnpm をインストール
RUN npm install -g pnpm

WORKDIR /app

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY . .

CMD ["pnpm", "dev"]